### ISSUE TITLE
library name/electron-rebuild

### ISSUE THREAD

**Issue by rokit** [asaladino/electron-rust#1]
Hi, thanks for sharing this. It helped me a lot. Just wanted to let you know of a few problems I had. One, this command didn't work:
`./node_modules/.bin/electron-rebuild`
because electron-rebuild is not actually part of the project. You must have had it installed globally? I had to add electron-rebuild to the project myself. The command is also a little different on Windows:
`.\node_modules\.bin\electron-rebuild.cmd`

Second, on line 69 of index.html the library name is wrong. It says "libfibonacci". It should just be "fibonacci".

**Comment by asaladino** [comment]
Nice catch and I'm glad it was helpful to you. I probably won't fix it. This was more of an experiment to see how electron and native code work together.
