### ISSUE TITLE
Wasm-bindgen version

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [asaladino/electron-rust#2]
Hi! Great little sample app to help people get going.

As rust is moving quickly to use wasm and wasm-bindgen, how would you change your app to use that?

I have working waasm-bindgen apps and yours and am trying to merge them....

**Comment by asaladino** [comment]
Good question Andrew. For this app, I'm not sure I would change anything. I was mostly exploring what kind of native access I could get with electron and when electron might be good option for building a cross-platform desktop app. With electron I can get a consistent UI/UX and make any native call with ffi and rust.

I guess with wasm you could get the speed of native and not have to compile for every platform. It might be fun to try.

**Comment by andrewdavidmackenzie** [comment]
A somewhat unrelated question. I have a crate/library in a separate directory that I also compile to wasm-unknown-unknown, and so I cannot specify `crate-type = ["dylib"]` for it (or it won't compile)...

Do you know how I can make it a dependency of this style of electron-rust project (which needs a dylib)?

**Comment by andrewdavidmackenzie** [comment]
Thanks for the first reply btw. I think it's good the example is small, focused and easy to reproduce. I am now experimenting with both those approaches (other is wasm_bindgen and wasm_pack - which works fine, but I'm havin gtrouble getting electron work well with web-pack...)

A possible extension to the example, might be to extend to cover packaging of the electron app with the platform specific binaries compiled, and how could you package and distribute an app for Win/Mac/Linux with this approach.

**Comment by asaladino** [comment]
You seemed to be more skilled than I in this area. My rust has, well... gotten rusty. These days my work is mostly focused on kotlin, java, node, php and python. However, you are making want to dip my toes into wasm world. Best of luck on your search.
